name: Build Raptur for macOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Homebrew dependencies
      run: |
        brew install ffmpeg rubberband
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Prepare native binaries for bundling
      run: |
        mkdir -p native_bins
        
        # Copy ffmpeg and related binaries
        cp $(brew --prefix)/bin/ffmpeg native_bins/
        cp $(brew --prefix)/bin/ffprobe native_bins/
        
        # Copy rubberband binary
        cp $(brew --prefix)/bin/rubberband native_bins/
        
        # Copy required dylibs for ffmpeg
        mkdir -p native_libs
        
        # Get list of dependencies and copy them
        for bin in native_bins/*; do
          for lib in $(otool -L "$bin" | grep -E '/opt/homebrew|/usr/local' | awk '{print $1}'); do
            if [ -f "$lib" ]; then
              cp -n "$lib" native_libs/ 2>/dev/null || true
            fi
          done
        done
        
        # Also copy rubberband library specifically
        cp $(brew --prefix)/lib/librubberband*.dylib native_libs/ 2>/dev/null || true
        cp $(brew --prefix)/lib/libsndfile*.dylib native_libs/ 2>/dev/null || true
        cp $(brew --prefix)/lib/libsamplerate*.dylib native_libs/ 2>/dev/null || true
        
        echo "Native binaries prepared:"
        ls -la native_bins/
        echo "Native libraries:"
        ls -la native_libs/
    
    - name: Build macOS app with PyInstaller
      run: |
        pyinstaller \
          --name "Raptur" \
          --onedir \
          --windowed \
          --collect-all streamlit \
          --copy-metadata streamlit \
          --collect-all librosa \
          --collect-all pydub \
          --collect-all pyloudnorm \
          --collect-all pyrubberband \
          --collect-all soundfile \
          --hidden-import streamlit.runtime.scriptrunner.magic_funcs \
          --add-data "app.py:." \
          --add-data "attached_assets:attached_assets" \
          --add-binary "native_bins/ffmpeg:." \
          --add-binary "native_bins/ffprobe:." \
          --add-binary "native_bins/rubberband:." \
          run_raptur.py
        
        # Copy native libraries into the app bundle
        cp native_libs/*.dylib dist/Raptur.app/Contents/MacOS/ 2>/dev/null || true
        cp native_libs/*.dylib dist/Raptur.app/Contents/Frameworks/ 2>/dev/null || mkdir -p dist/Raptur.app/Contents/Frameworks && cp native_libs/*.dylib dist/Raptur.app/Contents/Frameworks/ || true
    
    - name: Create distribution zip
      run: |
        cd dist
        zip -r Raptur-macOS.zip Raptur.app
        mv Raptur-macOS.zip ../
    
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Raptur-macOS
        path: Raptur-macOS.zip
        retention-days: 30
